default:
    type:     rest
    resource: CoreBundle\Controller\DefaultController
project:
    type:     rest
    resource: CoreBundle\Controller\ProjectController
announcement:
    type:     rest
    resource: CoreBundle\Controller\AnnouncementController
promise:
    type:     rest
    resource: CoreBundle\Controller\PromiseController
