services:
#    core.example:
#        class: CoreBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    user.documents_uploader:
        class: CoreBundle\Service\FileUploader
        arguments: ['%associations_doc_directory%']
    user.images_uploader:
        class: CoreBundle\Service\FileUploader
        arguments: ['%accounts_images_directory%']
    projects.banners_uploader:
        class: CoreBundle\Service\FileUploader
        arguments: ['%projects_banners_directory%']