api_core:
    type:     rest
    resource: "@CoreBundle/Resources/config/routing.yml"
    name_prefix: api_

api_user:
    type:     rest
    resource: "@UserBundle/Resources/config/routing.yml"
    name_prefix: api_
