api_login_check:
   path: /login_check

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

api:
    type: rest
    resource: "routing_rest.yml"

#api_preflight:
#    path: /preflight
#    defaults: { _controller: CoreBundle:Cors:preflight }
