<?php

namespace CoreBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
	public function getByState($asso_id)
	{
		$query = $this->createQueryBuilder('p')
			->select('COUNT(p)')
			->setParameter('asso_id', $asso_id)
			->where('p.association = :asso_id')
			->AndWhere('p.state = 1')
			->getQuery();

		return $query->getSingleScalarResult();
	}
}
 