<?php

namespace CoreBundle\Repository;

/**
 * promiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromiseRepository extends \Doctrine\ORM\EntityRepository
{
}
