<?php

namespace CoreBundle\Repository;

/**
 * ReceiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceiveRepository extends \Doctrine\ORM\EntityRepository
{
	public function getById($asso_id,$announce_id)
	{
		$query = $this->createQueryBuilder('a')
			->setParameter('asso_id', $asso_id)
			->setParameter('announce_id', $announce_id)
			->where('a.association = :asso_id')
			->AndWhere('a.announcement = :announce_id')
			->getQuery();

		return $query->getResult();
	}
}
