<?php

namespace CoreBundle\Repository;

/**
 * TypeExchangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeExchangeRepository extends \Doctrine\ORM\EntityRepository
{
}
