<?php

namespace CoreBundle\Repository;

/**
 * TypeMaterialsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeMaterialsRepository extends \Doctrine\ORM\EntityRepository
{
}
