<?php

namespace CoreBundle\Repository;

/**
 * TypeUserAdsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeUserAdsRepository extends \Doctrine\ORM\EntityRepository
{
}
