FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties: 
        username: 
            expose: true
        roles:
            expose: true
            groups : [details-user]
        enabled:
            expose: true
            groups : [details-user]
        email:
            expose: true
            groups : [me]
